### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by shudderdev** [mwarger/globomantics-react-ts#1]
Can't run application after install with "npm install" or "yarn install".
Got an error
"react-scripts" cannot be found.

**Comment by mwarger** [comment]
@shudderdev You'll need to make sure to `cd` into the `app` directory and `api` directory to install the dependencies for each of the subdirectories.  I will update the README to make this more clear.

**Comment by mwarger** [comment]
@shudderdev I've added a command that should get things setup for you.  You can run `yarn install-deps` or `npm run install-deps` from the root of the project for it to install the dependencies for the subdirectories in the application.
