### ISSUE TITLE
Missing files in main branch

### ISSUE THREAD

**Issue by TJSun009** [mwarger/globomantics-react-ts#9]
Hi @mwarger. I'm doing your course on Pluralsight - Building React Apps with TypeScript. I'm on the using hooks with Typescript part and I noticed that whilst in the Session folder you have other files,  such as VanillaJS SessionForm in the video, this isn't what I have on my clone of the main branch.

When I've tried to clone the m4 branch instead, which does have them, I've had issues with installing dependencies. The yarn install-deps command won't work either. Is it possible to add these other files to the main branch?

**Comment by mwarger** [comment]
@TJSun009 I'm looking into this.  Thanks for letting me know.

**Comment by mwarger** [comment]
@TJSun009 I've added the install-deps command to the m4 branches.  This should resolve the installation issue.  You can also copy the command over from the main branch, or run `yarn install` in the `api` and `app` folders to install all the dependencies.  If you have any more questions, please let me know.  Thank you for checking out the course!

**Comment by TJSun009** [comment]
@mwarger I really appreciate the help.
